### ISSUE TITLE
[Feature]: Duolingo-style UI for the entire app

### ISSUE THREAD

**Issue by naida93** [hpi-swa-teaching/SqueakLanguageLearning#1]
**User Story :** 

As a user, I want a start-page, so that I can overview of my learning prosess visually nicely and also check other features such as PX, Badges etc.

**Acceptance Criteria :**
- [x] Topic & lesson buttons with colors corresponding with Not started-> ${\color{gray}Gray}$, Compeleted/test Passed-> ${\color{green}Green}$
- [x] Home button with Logo in the middle of the top part. 
- [x] Experience points and badges and displayed with icon
- [x] Nice color palette

**Mock-up**
It can be changed as we develop the application further.
<p align="center">
  <img src="https://github.com/hpi-swa-teaching/SqueakLanguageLearning/assets/40808293/0478c9dc-b27a-4d89-98e4-6f1cd7d70ec3" width=70% height=70%>
</p>

**Comment by matveysiva** [comment]
> **User Story :** As a user, I want a start-page, so that I can check how far I completed as I entered the application
> 
> **Acceptance Criteria :** Given that a icon of the application, When the user open the system(application), Then the system should show all levels, and the levels are not worked on yet will be in gray and which completed in green(the color can be changed as we decide later for the design)

Feedback

- Doesn't the part "so that I can check how far I completed " mean #7 
- Isn't "Then the system should show all level" the same as #2 
- What should the starting page contain?
- How do you launch the application, where is the icon?
