### ISSUE TITLE
[Feature]: App initialization with homepage displayed

### ISSUE THREAD

**Issue by alx-net** [hpi-swa-teaching/SqueakLanguageLearning#13]
As a learner, I want a Homepage inside of the app, from where I can start my Duolingo/Squeak learning journey.

Acceptance Criteria:

- [x]  The app can be initialized and opened in an easy way.
- [x]  When the app gets started, the learner will be navigated to the Homepage
- [x] The Homepage should be almost empty at this point. However it should provide enough space to include other UI elements

**Comment by matveysiva** [comment]
Include 

> As a learner, I want a Homepage inside of the app, from where I can start my Duolingo/Squeak learning journey.
> 
> Acceptance Criteria:
> 
> * [ ]   When the app gets started, the learner will be navigated to the Homepage
> * [ ]  The Homepage should be almost empty at this point. However it should provide enough space to include other UI elements

Feedback
- How do you open the app?
