### ISSUE TITLE
[Feature]: Remember the progress of the app

### ISSUE THREAD

**Issue by charlieliu219** [hpi-swa-teaching/SqueakLanguageLearning#16]
As a user, I want to able to save my progress so I won't have to start over again after closing the App and opening it again at another time. 

Acceptance criteria:
- [x] There is an icon visible from any page for displaying the collected points
- [x] After completing the task, the collected score would be updated.
- [x] After re-opening the app, I'm able to see the points, collected before.
- [x] There is a possibility to reset the progress (by clicking reset-button, for example)

**Comment by naida93** [comment]
Could we change acceptance criteria to the following with less technical details:
 
1. After re-opening the app, I'm able to see which tasks I've already completed. This need to be specified, of course, how exactly I could see it, for example colour of the lesson title is different.
2. There is a possibility to reset the progress (by clicking reset-button, for example).

**Comment by naida93** [comment]
And then could we create a separate story for some really simple system of rewards, like for example 1 Point per completed task? And, probably, for another sprint.
With acceptance criteria like:
1. There is an icon visible from any page for displaying the collected points.
2. After completing the task, the collected score would be updated.
3. After re-opening the app, I'm able to see the points, collected before.

Everything is negotiable, just a suggestion ;)

**Comment by wolfSarah** [comment]
Technical Information:

- [ ] Store which lessons are completed and which are not
- [ ] (Store XP-Count and Badges) (optional)
- [ ] Use a local file for storing
- [ ] When App launches, read from that file (create a new one, if there isn't one yet)
- [ ] When App is closed, overwrite file with Information on Progress
