### ISSUE TITLE
[Feature]: Display a lesson on a subpage for a specific topic

### ISSUE THREAD

**Issue by charlieliu219** [hpi-swa-teaching/SqueakLanguageLearning#24]
As a user I want to see different lessons when I click on a specific subtopic (like "data type - string") and I want to see the lesson, when clicking on it.

Acceptance Criteria:
- [x] When the user clicks on the subtopic all the lessons under this subtopic are displayed on the subpage
- [x] When clicking on a lesson a concrete Lesson with a description (What to do in this Task Type), a question (additional information, optional), an interaction part (e.g. Multiple Choice), a field for the status text (Success or Failure) and a Submit-Button is shown
- [x] When clicking the Submit Button the Input from the User is validated and the status text shows the result

Structure of Lessonpage:
![image](https://github.com/hpi-swa-teaching/SqueakLanguageLearning/assets/130765617/84bc443f-a1c5-40fc-a168-9b5ae17ae71b)

**Comment by wolfSarah** [comment]
Technical Information:
- [ ] There should be a class that stores the content for each lesson (eg. for a multiple choice lesson, the content includes: the question, the options, the right answers).
- [ ] When the user clicks on the subtopic, lessons under this subtopic are created based on a content class and displayed on the subpage.
