### ISSUE TITLE
Small lessons

### ISSUE THREAD

**Issue by naida93** [hpi-swa-teaching/SqueakLanguageLearning#3]
As a learner I want to have small lessons to learn step by step.

Acceptance Criteria:

When a user clicks on a lesson, then they are confronted with a task of only one type (e.g. filling gaps in a text, multiple choice).

**Comment by matveysiva** [comment]
> As a learner I want to have small lessons to learn step by step.
> 
> Acceptance Criteria:
> 
> When a user clicks on a lesson, then they are confronted with a task of only one type (e.g. filling gaps in a text, multiple choice).

Feedback

- Having "small lessons" doesn't mean that you "learn step by step".
- Please divide different task types into different stories and describe how they work. (E.g. Mulitple Choice Questions)
- In this context you could also include example questions
