### ISSUE TITLE
[Feature]: Naviagtion between Pages

### ISSUE THREAD

**Issue by wolfSarah** [hpi-swa-teaching/SqueakLanguageLearning#34]
As a User I want to be able to navigate back from a page to its previous layer.

e.g. When in a specific Lesson and clicking on "Back" the User is directed to the Subtopicpage with all its lessons.

AC:
- [x] Back-Button on every page
- [x] When clicking this button the User is redirected to the previous layer

**Comment by naida93** [comment]
I would suggest create a controller class to handle all the navigation (of course, if we would decide to take on the suggestion to use model-view-controller pattern).
