### ISSUE TITLE
Allow a LessonPage to display code in a code block

### ISSUE THREAD

**Issue by charlieliu219** [hpi-swa-teaching/SqueakLanguageLearning#38]
As a User I (sometimes) want code blocks in lesson to get a better connection to actual smalltalk code and also try things out on myself.

<img width="880" alt="image" src="https://github.com/hpi-swa-teaching/SqueakLanguageLearning/assets/125988414/e373aed4-79ba-425e-b8b1-cd79d08dd9bd">

AC:
- [x] When a lesson requires user to read a piece of code and then answer a multi choice question / close, the code can be displayed in the proper code mode instead of plain text.
- [x] The User can run code in the Code Block
- [x] The User can write code in the Code Block
- [x] If no code is needed to be displayed, display nothing

**Comment by wolfSarah** [comment]
- [x] If instead of code, a textual information should be displayed, then display the textual information as plain text.
- [ ] If an image needs to be displayed here, display image 
...
