### ISSUE TITLE
Release 3 Feedback

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/SqueakLanguageLearning#47]
Hi, just tried your new release.

Feel free to use this feedback if it's helpful / in accord with your customer. The installation and trying the lessons worked :) Things I noticed:
- Currently, I have to navigate back to the overview and remember what I just solved to get to the next lessen. A "next lesson" button that leads to the next lesson (Koans style) or the overview (Duolingo style) might help. Also marking the already solved lessons in some way might help.
- Your second assignment lesson is a bit unusual (x := y := 6). This only works for assignment to Integers (and is kinda unsual in general). Maybe move this from "assignment" to a "fun fact" category; it is unsual, but through your lesson I just learned that Squeak supports this :D
- I would have liked to see all code at once the Integer lessons instead of using a scrollbar.
- Also, your first two Integer lessons are very hard :D Maybe start with easy things like the class name, an increment, or a more simple equation.

Good luck with your project

**Comment by yeji0205** [comment]
We implemented all the feedbacks.
