### ISSUE TITLE
Display learning progress

### ISSUE THREAD

**Issue by yeji0205** [hpi-swa-teaching/SqueakLanguageLearning#7]
As a user, I want to see my progress in learning so that I can track my improvement over time.

**Comment by naida93** [comment]
Given a user interacts with the app,
When the user navigates to [the home screen?],
Then the user's learning progress is prominently displayed.

Given a user interacts with the app,
When the user updates their progress by completing lessons and exercises,
Then the progress tracking feature updates in real-time.

**Comment by matveysiva** [comment]
> Given a user interacts with the app, When the user navigates to [the home screen?], Then the user's learning progress is prominently displayed.
> 
> Given a user interacts with the app, When the user updates their progress by completing lessons and exercises, Then the progress tracking feature updates in real-time.

Feedback

- Very unspecific, how should the progress be tracked? In percentage or amount of lessons? What exactly do you want to display
- Do you just want it displayed or should it be interactable?
