### ISSUE TITLE
[Feature]: Reward System

### ISSUE THREAD

**Issue by yeji0205** [hpi-swa-teaching/SqueakLanguageLearning#8]
As a user, I want to earn rewards for completing lessons to stay motivated.

Acceptance criteria:
- [x] A reward is an icon of a cheese and a corresponding number of points displayed in the top right corner of the screen.
- [x] A user earns a badge on completing the whole topic.
- [x] There is an icon for a badge displayed in the header of a page with a count next to (count shows how many badges where earned)

**Comment by naida93** [comment]
Given a user launches the app,
When they successfully complete a task,
Then the reward earned for that task is securely saved in the user's profile,
And the reward becomes visible within the "Rewards" section of the app interface,
The user can access the "Rewards" section to view their accumulated rewards and track their progress.

**Comment by matveysiva** [comment]
How d

> Given a user launches the app, When they successfully complete a task, Then the reward earned for that task is securely saved in the user's profile, And the reward becomes visible within the "Rewards" section of the app interface, The user can access the "Rewards" section to view their accumulated rewards and track their progress.

Feedback
- How do the rewards look like? Do you just want to build in special badges or something else?
- In this context how should the reward page look like?
